In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import folium
from folium import plugins

store = pd.read_csv('강서구 편의점.csv')

In [ ]:
store.head(10)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,20698098,CU,강서태양점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,베스트힐타운,서울특별시 강서구 강서로18길 146,157010,7745,NaN,1,NaN,126.853607,37.535125
1,24269630,세븐일레븐,화곡수명점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,NaN,서울특별시 강서구 강서로33길 103,157924,7711,NaN,1,NaN,126.834220,37.540522
2,24218680,세븐일레븐,강서내발산길점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,신약국,서울특별시 강서구 강서로45라길 35,157835,7638,NaN,1,NaN,126.834082,37.549387
3,28524181,CU,수명파크점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,마곡수명산파크3단지아파트,서울특별시 강서구 수명로1길 110,157933,7643,NaN,1,NaN,126.824639,37.551852
4,11719625,CU,마곡아르디에점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,아르디에,서울특별시 강서구 강서로 423,157210,7792,NaN,1,NaN,126.839341,37.563495
5,14974657,이마트,24강서내발산점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,NaN,서울특별시 강서구 강서로47다길 20,157831,7638,NaN,1,NaN,126.834110,37.551973
6,26003806,GS25등촌스타점,등촌스타점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,한산교회,서울특별시 강서구 등촌로39길 6,157030,7668,NaN,1,NaN,126.862002,37.545577
7,16098527,CU,우장산역점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,세란빌딩,서울특별시 강서구 강서로 251,157835,7639,NaN,1,NaN,126.836003,37.548117
8,16173297,썬플러스,NaN,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,삼부르네상스오피스텔,서울특별시 강서구 양천로 482,157033,7575,NaN,NaN,NaN,126.853909,37.561249
9,26283264,CU방화진흥점,방화진흥점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,삼미아파트,서울특별시 강서구 초원로 30,157220,7613,NaN,1,NaN,126.808431,37.567575

In [ ]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   상가업소번호     443 non-null    int64
 1   상호명        443 non-null    object
 2   지점명        385 non-null    object
 3   상권업종대분류코드  443 non-null    object
 4   상권업종대분류명   443 non-null    object
 5   상권업종중분류코드  443 non-null    object
 6   상권업종중분류명   443 non-null    object
 7   상권업종소분류코드  443 non-null    object
 8   상권업종소분류명   443 non-null    object
 9   표준산업분류코드   443 non-null    object
 10  표준산업분류명    443 non-null    object
 11  시도코드       443 non-null    int64
 12  시도명        443 non-null    object
 13  시군구코드      443 non-null    int64
 14  시군구명       443 non-null    object
 15  행정동코드      443 non-null    int64
 16  행정동명       443 non-null    object
 17  법정동코드      443 non-null    int64
 18  법정동명       443 non-null    object
 19  지번코드       443 non-null    float64
 20  대지구분코드     443 non-null    int64
 21  대지구분명      443 non-null    object
 22  지번본번지      443 non-null    int64
 23  지번부번지      341 non-null    float64
 24  지번주소       443 non-null    object
 25  도로명코드      443 non-null    float64
 26  도로명        443 non-null    object
 27  건물본번지      443 non-null    int64
 28  건물부번지      29 non-null     float64
 29  건물관리번호     443 non-null    float64
 30  건물명        288 non-null    object
 31  도로명주소      443 non-null    object
 32  구우편번호      443 non-null    int64
 33  신우편번호      443 non-null    int64
 34  동정보        35 non-null     object
 35  층정보        348 non-null    object
 36  호정보        0 non-null      float64
 37  경도         443 non-null    float64
 38  위도         443 non-null    float64
dtypes: float64(8), int64(10), object(21)
memory usage: 135.1+ KB

In [ ]:
store.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

### 분석에서 활용할 수 있는 정보
##### 상호명, 지점명, 행정동명, 법정동명, 도로명주소, 층정보, 경도, 위도
- 상호명, 지점명: 웹 검색을 통한 실제 편의점의 정보 확인 가능
- 행정동명, 법정동명: 동별 편의점 통계 확인 가능
- 층정보: 장애인들이 사용하기에 편리한지의 여부
- 도로명주소, 경도, 위도: 지도에 시각화 시, 활용 가능

In [ ]:
store_need = store[['상호명','지점명','행정동명','법정동명','도로명주소','층정보','경도','위도']]

In [ ]:
store_need

,상호명,지점명,행정동명,법정동명,도로명주소,층정보,경도,위도
0,CU,강서태양점,화곡2동,화곡동,서울특별시 강서구 강서로18길 146,1,126.853607,37.535125
1,세븐일레븐,화곡수명점,화곡3동,화곡동,서울특별시 강서구 강서로33길 103,1,126.834220,37.540522
2,세븐일레븐,강서내발산길점,발산1동,내발산동,서울특별시 강서구 강서로45라길 35,1,126.834082,37.549387
3,CU,수명파크점,발산1동,내발산동,서울특별시 강서구 수명로1길 110,1,126.824639,37.551852
4,CU,마곡아르디에점,가양1동,마곡동,서울특별시 강서구 강서로 423,1,126.839341,37.563495
...,...,...,...,...,...,...,...,...
438,코리아세븐김포공항버스정류장점,NaN,공항동,공항동,서울특별시 강서구 하늘길 112,1,126.808457,37.556745
439,코리아세븐가양9단지점,NaN,가양3동,가양동,서울특별시 강서구 허준로 234,1,126.863355,37.558547
440,코리아세븐마곡,벽산점,가양1동,마곡동,서울특별시 강서구 양천로47길 118,NaN,126.836831,37.575634
441,코리아세븐마곡이너매스점,NaN,가양1동,마곡동,서울특별시 강서구 마곡중앙6로 21,NaN,126.829603,37.560822
442,이마트,24강서화곡마을점,화곡2동,화곡동,서울특별시 강서구 등촌로13바길 98,NaN,126.854998,37.534418

In [ ]:
# 상호명이 결측치인 행은 없으며,
# 지점명이 결측치인 행은 58개이며, 상호명이 지점명으로 되어있거나 프랜차이즈의 이름만 나와있는 경우이다.

display(store_need[store_need['상호명'].isnull()])
display(store_need[store_need['지점명'].isnull()])

Empty DataFrame
Columns: [상호명, 지점명, 행정동명, 법정동명, 도로명주소, 층정보, 경도, 위도]
Index: []

,상호명,지점명,행정동명,법정동명,도로명주소,층정보,경도,위도
8,썬플러스,NaN,등촌3동,등촌동,서울특별시 강서구 양천로 482,NaN,126.853909,37.561249
17,CU,NaN,방화1동,방화동,서울특별시 강서구 초원로16길 24,1,126.815049,37.566452
18,SK네트웍스해바라기,NaN,화곡6동,화곡동,서울특별시 강서구 화곡로 273,1,126.846951,37.549270
26,CU,NaN,등촌3동,등촌동,서울특별시 강서구 양천로 460,1,126.851681,37.562570
27,"C,U정원점",NaN,화곡6동,화곡동,서울특별시 강서구 공항대로46길 57,1,126.852001,37.553500
41,GS25화곡풀향기,NaN,화곡3동,화곡동,서울특별시 강서구 강서로35길 8,1,126.838403,37.542969
56,24시편의점,NaN,등촌3동,등촌동,서울특별시 강서구 강서로56길 38,1,126.840653,37.559183
66,세븐일레븐가양프라자점B,NaN,가양3동,가양동,서울특별시 강서구 허준로 198,1,126.860246,37.561302
82,지에스25화곡달빛,NaN,화곡1동,화곡동,서울특별시 강서구 곰달래로16길 29,1,126.840366,37.528752
85,씨유화곡소비자,NaN,우장산동,화곡동,서울특별시 강서구 화곡로31길 53,1,126.840440,37.544385
89,지에스25발산1단지,NaN,발산1동,내발산동,서울특별시 강서구 강서로47길 108,NaN,126.830521,37.553514
100,세븐일레븐,NaN,화곡8동,화곡동,서울특별시 강서구 강서로 54,B1,126.846596,37.531948
101,지에스25마곡14단지,NaN,발산1동,마곡동,서울특별시 강서구 마곡중앙로 33,1,126.824067,37.558036
146,세븐일레븐,NaN,화곡1동,화곡동,서울특별시 강서구 화곡로 142,1,126.837569,37.540555
173,에스아이씨유,NaN,화곡3동,화곡동,서울특별시 강서구 화곡로 119,NaN,126.835093,37.540431
176,GS25,NaN,염창동,염창동,서울특별시 강서구 공항대로65길 51,1,126.869920,37.550312
181,제이케이블라썸편의점,NaN,염창동,염창동,서울특별시 강서구 양천로65길 41-22,1,126.867615,37.556759
184,GS25화곡본,NaN,화곡본동,화곡동,서울특별시 강서구 까치산로 72,NaN,126.847152,37.545019
186,인더라인25시편의점,NaN,등촌1동,등촌동,서울특별시 강서구 공항대로61길 13,1,126.865373,37.551674
196,지에스25방화대림,NaN,방화2동,방화동,서울특별시 강서구 양천로6길 57,1,126.808015,37.569553
199,지에스25등촌캐빈,NaN,등촌1동,등촌동,서울특별시 강서구 공항대로51길 17,1,126.857397,37.555183
203,GEESSI신발편의점,NaN,화곡8동,화곡동,서울특별시 강서구 강서로18길 8-9,NaN,126.846507,37.533281
211,비지에프휴먼넷항공지원센터점,NaN,공항동,과해동,서울특별시 강서구 하늘길 70,NaN,126.796353,37.561983
216,데이앤나이트,NaN,화곡8동,화곡동,서울특별시 강서구 강서로18길 15,1,126.846451,37.533965
217,편의점사랑,NaN,화곡8동,화곡동,서울특별시 강서구 곰달래로25길 57,1,126.848263,37.533154
219,비지에프리테일화곡보리점,NaN,화곡6동,화곡동,서울특별시 강서구 화곡로51길 13,1,126.847329,37.550427
226,서울식물원푸드이마트24편의점,NaN,가양1동,마곡동,서울특별시 강서구 마곡중앙로 136,4,126.832900,37.572234
227,휴게음식점,NaN,방화2동,방화동,서울특별시 강서구 하늘길 38,2,126.802937,37.571357
231,GS25마곡8단지,NaN,방화1동,마곡동,서울특별시 강서구 마곡서1로 81,1,126.819134,37.564357
232,씨유한솔할인마트,NaN,염창동,염창동,서울특별시 강서구 양천로63길 38,1,126.865869,37.557004
234,보광훼미리마트화곡수명,NaN,화곡3동,화곡동,서울특별시 강서구 강서로33길 103,NaN,126.834220,37.540522
239,편의점&카페24,NaN,화곡4동,화곡동,서울특별시 강서구 등촌로 3,1,126.863524,37.530274
246,코리아세븐등촌샤르망,NaN,등촌1동,등촌동,서울특별시 강서구 공항대로45길 101,1,126.857628,37.559303
258,내발산GS,NaN,발산1동,내발산동,서울특별시 강서구 강서로47가길 38,1,126.835439,37.550896
312,이마트24,NaN,가양1동,마곡동,서울특별시 강서구 마곡중앙6로 89,1,126.837276,37.560158
324,지에스25방화샤르망,NaN,방화3동,방화동,서울특별시 강서구 방화대로47가길 7,1,126.812987,37.576523
325,훼미리마트화곡PMK,NaN,화곡1동,화곡동,서울특별시 강서구 곰달래로 77,1,126.841280,37.530356
329,코레일유통김포공항편의점,NaN,공항동,공항동,서울특별시 강서구 하늘길 111,3,126.803342,37.558774
331,백컵스,NaN,가양1동,가양동,서울특별시 강서구 양천로 351,1,126.841846,37.568349
355,씨제이올리브네트웍스송정,NaN,공항동,공항동,서울특별시 강서구 공항대로 28,1,126.810266,37.561133
357,우장산점,NaN,우장산동,내발산동,서울특별시 강서구 우장산로4길 59,1,126.838853,37.551912
367,티엠씨에이치,NaN,화곡6동,화곡동,서울특별시 강서구 공항대로 376,1,126.847174,37.556841
378,지에스화곡들판점,NaN,화곡2동,화곡동,서울특별시 강서구 곰달래로 205,1,126.855789,37.531524
379,비지에프리테일화곡1동점,NaN,우장산동,화곡동,서울특별시 강서구 화곡로27가길 2,1,126.840768,37.542244
382,GS25화곡대원,NaN,화곡3동,화곡동,서울특별시 강서구 화곡로21길 87,NaN,126.835898,37.544683
394,씨유티,NaN,발산1동,마곡동,서울특별시 강서구 마곡중앙2로 35,4,126.830519,37.557983
406,지에스화곡나누리점,NaN,화곡1동,화곡동,서울특별시 강서구 가로공원로 188,1,126.836902,37.536890
407,착한가게24,NaN,화곡8동,화곡동,서울특별시 강서구 강서로12길 31,1,126.848676,37.532059
411,헬시박스,NaN,방화2동,방화동,서울특별시 강서구 양천로14길 35,1,126.810100,37.571529
426,코리아세븐화곡우장산숲점,NaN,우장산동,화곡동,서울특별시 강서구 화곡로31길 22,1,126.842174,37.544258
431,코리아세븐염창래미안점,NaN,염창동,염창동,서울특별시 강서구 양천로 646-32,1,126.867901,37.552113
432,코리아세븐화곡자하클래식점,NaN,화곡본동,화곡동,서울특별시 강서구 화곡로 262,1,126.846868,37.548026
433,인더라인25,NaN,가양1동,마곡동,서울특별시 강서구 마곡서로 152,1,126.825623,37.567747
434,온기,NaN,염창동,염창동,서울특별시 강서구 양천로 660,NaN,126.870085,37.552124
435,코리아세븐항공지원센터점,NaN,공항동,과해동,서울특별시 강서구 하늘길 70,1,126.796353,37.561983
438,코리아세븐김포공항버스정류장점,NaN,공항동,공항동,서울특별시 강서구 하늘길 112,1,126.808457,37.556745
439,코리아세븐가양9단지점,NaN,가양3동,가양동,서울특별시 강서구 허준로 234,1,126.863355,37.558547
441,코리아세븐마곡이너매스점,NaN,가양1동,마곡동,서울특별시 강서구 마곡중앙6로 21,NaN,126.829603,37.560822

In [ ]:
# 주소 관련 컬럼들은 결측치를 가지고 있는 행이 없다.

display(store_need[store_need['행정동명'].isnull()])
display(store_need[store_need['법정동명'].isnull()])
display(store_need[store_need['도로명주소'].isnull()])

Empty DataFrame
Columns: [상호명, 지점명, 행정동명, 법정동명, 도로명주소, 층정보, 경도, 위도]
Index: []

Empty DataFrame
Columns: [상호명, 지점명, 행정동명, 법정동명, 도로명주소, 층정보, 경도, 위도]
Index: []

Empty DataFrame
Columns: [상호명, 지점명, 행정동명, 법정동명, 도로명주소, 층정보, 경도, 위도]
Index: []

In [ ]:
# 층정보 컬럼이 결측치인 행은 95개이다.

display(store_need[store_need['층정보'].isnull()])

,상호명,지점명,행정동명,법정동명,도로명주소,층정보,경도,위도
8,썬플러스,NaN,등촌3동,등촌동,서울특별시 강서구 양천로 482,NaN,126.853909,37.561249
13,GS25,염창사랑점,염창동,염창동,서울특별시 강서구 양천로73길 80,NaN,126.874139,37.554245
14,CU,등촌두산점,등촌1동,등촌동,서울특별시 강서구 양천로 564,NaN,126.861555,37.557124
16,CU,마곡푸르지오점,가양1동,마곡동,서울특별시 강서구 마곡중앙6로 10,NaN,126.828172,37.560375
23,GS25,마곡파크뷰점,가양1동,마곡동,서울특별시 강서구 마곡중앙6로 85,NaN,126.836856,37.560235
...,...,...,...,...,...,...,...,...
430,이마트,24R공항대로점,공항동,공항동,서울특별시 강서구 공항대로2길 64,NaN,126.808576,37.558503
434,온기,NaN,염창동,염창동,서울특별시 강서구 양천로 660,NaN,126.870085,37.552124
440,코리아세븐마곡,벽산점,가양1동,마곡동,서울특별시 강서구 양천로47길 118,NaN,126.836831,37.575634
441,코리아세븐마곡이너매스점,NaN,가양1동,마곡동,서울특별시 강서구 마곡중앙6로 21,NaN,126.829603,37.560822
442,이마트,24강서화곡마을점,화곡2동,화곡동,서울특별시 강서구 등촌로13바길 98,NaN,126.854998,37.534418

In [ ]:
# 경도, 위도 컬럼이 결측치인 행은 없다.

display(store_need[store_need['경도'].isnull()])
display(store_need[store_need['위도'].isnull()])

Empty DataFrame
Columns: [상호명, 지점명, 행정동명, 법정동명, 도로명주소, 층정보, 경도, 위도]
Index: []

Empty DataFrame
Columns: [상호명, 지점명, 행정동명, 법정동명, 도로명주소, 층정보, 경도, 위도]
Index: []

In [ ]:
# 법정동별로 편의점의 개수를 보았을 때, 화곡동/마곡동/등촌동 순으로 개수가 많은 것을 알 수 있다

store_need.groupby(['법정동명']).count().상호명.sort_values(ascending = False)

법정동명
화곡동     144
마곡동      85
등촌동      60
방화동      41
염창동      32
가양동      26
내발산동     23
공항동      21
개화동       4
외발산동      4
과해동       3
Name: 상호명, dtype: int64

In [ ]:
# 행정동을 기준으로 보면, 가양1동/화곡1동/발산1동 순으로 개수가 많은 것을 알 수 있다

store_need.groupby(['행정동명']).count().상호명.sort_values(ascending = False)

행정동명
가양1동    70
화곡1동    38
발산1동    34
등촌1동    32
염창동     32
공항동     30
화곡6동    24
방화1동    21
화곡본동    21
방화2동    20
화곡3동    17
등촌3동    16
우장산동    16
화곡8동    14
화곡4동    13
등촌2동    12
방화3동    11
화곡2동     9
가양2동     8
가양3동     5
Name: 상호명, dtype: int64

In [ ]:
store_need.지점명.fillna('',inplace=True)

C:\Users\chlwj\AppData\Local\Temp\ipykernel_18944\3172024585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  store_need.지점명.fillna('',inplace=True)

In [ ]:
location_data = store_need[['위도','경도']].values[:len(store_need)].tolist()
center =[store_need.위도.mean(),store_need.경도.mean()]

In [ ]:
map = folium.Map(location=center,zoom_start=13,width='70%')

In [ ]:
for i in range(len(store_need)):
    store_name=(str(store_need['상호명'][i]+' '+store_need['지점명'][i]))
    store_color='black'
    folium.Circle(location=location_data[i],radius=1,color=store_color,fill=True,fill_opacity=1, tooltip=store_name).add_to(map)

plugins.HeatMap(location_data,radius=18).add_to(map)

In [ ]:
map

#### 마곡나루역, 가양역, 발산역, 까치산역 근처에 편의점이 밀집해있는 것을 확인 가능

In [ ]:
location_data

[[37.53512526, 126.853607],
 [37.54052187, 126.8342201],
 [37.54938668, 126.834082],
 [37.55185198, 126.824639],
 [37.56349459, 126.8393406],
 [37.55197291, 126.8341097],
 [37.54557739, 126.8620021],
 [37.54811715, 126.836003],
 [37.56124918, 126.8539086],
 [37.56757466, 126.8084314],
 [37.5299223, 126.8606447],
 [37.52779161, 126.8398488],
 [37.54425833, 126.8421737],
 [37.55424457, 126.8741386],
 [37.55712434, 126.8615549],
 [37.57818364, 126.813289],
 [37.56037482, 126.8281723],
 [37.56645191, 126.8150485],
 [37.54926978, 126.8469511],
 [37.54987555, 126.873299],
 [37.53029522, 126.844313],
 [37.56088596, 126.854548],
 [37.55989699, 126.8455197],
 [37.56023543, 126.8368558],
 [37.56929501, 126.8254517],
 [37.5502768, 126.8634584],
 [37.56257007, 126.8516812],
 [37.55349979, 126.8520014],
 [37.5475896, 126.8218768],
 [37.54468318, 126.835898],
 [37.57004743, 126.8159877],
 [37.55472522, 126.8191162],
 [37.56895334, 126.825525],
 [37.52858218, 126.8442036],
 [37.56796495, 126.8267064],
 [37.53061983, 126.8452583],
 [37.55461733, 126.8613327],
 [37.55860764, 126.826242],
 [37.54773764, 126.8758774],
 [37.5575253, 126.8582891],
 [37.56457177, 126.8099734],
 [37.54296885, 126.8384028],
 [37.56955272, 126.808015],
 [37.52813337, 126.8416197],
 [37.52975595, 126.8472176],
 [37.54923097, 126.8605885],
 [37.55926417, 126.8261185],
 [37.5303556, 126.8412799],
 [37.56350178, 126.8428267],
 [37.54705485, 126.824273],
 [37.54273314, 126.8364262],
 [37.56861315, 126.8257454],
 [37.55310936, 126.8703756],
 [37.55289716, 126.8511845],
 [37.54031409, 126.8405713],
 [37.5605394, 126.8338743],
 [37.55918253, 126.8406525],
 [37.53023984, 126.8395846],
 [37.57606625, 126.8106055],
 [37.55609911, 126.8123604],
 [37.56972842, 126.8419606],
 [37.57248651, 126.8076626],
 [37.55834502, 126.8134905],
 [37.53719037, 126.8593687],
 [37.55288395, 126.8323865],
 [37.56922958, 126.8261206],
 [37.56130152, 126.8602462],
 [37.52948939, 126.8466787],
 [37.55548481, 126.8597237],
 [37.55877421, 126.8033425],
 [37.56337664, 126.8076154],
 [37.54697503, 126.8472467],
 [37.54652541, 126.8464163],
 [37.55167379, 126.8653725],
 [37.55023878, 126.8773789],
 [37.5497646, 126.8231327],
 [37.55325463, 126.8499567],
 [37.54244174, 126.8471355],
 [37.54789328, 126.8471647],
 [37.55770687, 126.8612291],
 [37.55803636, 126.8240665],
 [37.56785503, 126.8274326],
 [37.52875179, 126.8403657],
 [37.57679266, 126.8102657],
 [37.52836757, 126.8471372],
 [37.54438548, 126.8404404],
 [37.56875291, 126.8407985],
 [37.54705333, 126.8749823],
 [37.56825286, 126.8403421],
 [37.55351422, 126.8305206],
 [37.56796495, 126.8267064],
 [37.56026188, 126.8123622],
 [37.56708489, 126.8270032],
 [37.56055788, 126.8375752],
 [37.55557955, 126.861137],
 [37.57018244, 126.840482],
 [37.55111088, 126.8649283],
 [37.56154197, 126.8543682],
 [37.57915581, 126.7980577],
 [37.56767397, 126.816512],
 [37.53194841, 126.8465956],
 [37.55803636, 126.8240665],
 [37.56678354, 126.827506],
 [37.56390789, 126.8310034],
 [37.55078461, 126.8694261],
 [37.56542431, 126.8195019],
 [37.56569318, 126.8476262],
 [37.55518601, 126.8651834],
 [37.56315875, 126.8529172],
 [37.56252823, 126.8128356],
 [37.54693672, 126.8516381],
 [37.54926978, 126.8469511],
 [37.55292842, 126.8341514],
 [37.54541149, 126.8412393],
 [37.53032564, 126.8539068],
 [37.57257179, 126.8143402],
 [37.56550158, 126.8400226],
 [37.54173335, 126.8428804],
 [37.53603325, 126.8496895],
 [37.54615953, 126.8357619],
 [37.5608215, 126.8296028],
 [37.57284496, 126.8092531],
 [37.55526037, 126.8729463],
 [37.55944265, 126.8553058],
 [37.53560924, 126.8617236],
 [37.54300013, 126.8170493],
 [37.54723288, 126.8322257],
 [37.53336772, 126.8516991],
 [37.56767397, 126.816512],
 [37.55341146, 126.8531119],
 [37.56353744, 126.8354575],
 [37.5804397, 126.7949576],
 [37.54883021, 126.8761213],
 [37.52922414, 126.8444313],
 [37.53233616, 126.8558899],
 [37.54134, 126.8496532],
 [37.54705333, 126.8749823],
 [37.56714705, 126.8269117],
 [37.56354066, 126.8104765],
 [37.53379733, 126.861638],
 [37.55931203, 126.8254952],
 [37.54597178, 126.8608531],
 [37.53916762, 126.8403515],
 [37.54850216, 126.8700717],
 [37.55725413, 126.853551],
 [37.55671277, 126.8618554],
 [37.54055489, 126.837569],
 [37.53627185, 126.8390838],
 [37.55314104, 126.8475479],
 [37.54725338, 126.8434627],
 [37.55848006, 126.8251914],
 [37.57669859, 126.8179428],
 [37.56875291, 126.8407985],
 [37.55695251, 126.8420339],
 [37.57152708, 126.8206848],
 [37.55311883, 126.865724],
 [37.56107618, 126.8408043],
 [37.55053688, 126.8736738],
 [37.57101653, 126.8465254],
 [37.56833299, 126.8184372],
 [37.55249066, 126.8391039],
 [37.56790778, 126.810192],
 [37.56128028, 126.8386506],
 [37.5549815, 126.8186141],
 [37.54847724, 126.8323195],
 [37.53164447, 126.8514653],
 [37.55963415, 126.8361861],
 [37.53910613, 126.8478771],
 [37.53559082, 126.8413007],
 [37.57170136, 126.8282326],
 [37.55407747, 126.8651549],
 [37.55378282, 126.8376465],
 [37.54826981, 126.8721575],
 [37.54043137, 126.8350928],
 [37.5630347, 126.852206],
 [37.53206901, 126.846028],
 [37.55031179, 126.8699199],
 [37.53543903, 126.8478883],
 [37.54438548, 126.8404404],
 [37.54881785, 126.8625979],
 [37.56905067, 126.8154262],
 [37.55675914, 126.8676155],
 [37.560141, 126.8318545],
 [37.53201463, 126.8617783],
 [37.54501886, 126.8471524],
 [37.557106, 126.8643281],
 [37.55167379, 126.8653725],
 [37.55975718, 126.8304004],
 [37.57437586, 126.8136437],
 [37.55107389, 126.847161],
 [37.56767397, 126.816512],
 [37.54705333, 126.8749823],
 [37.54506048, 126.8468009],
 [37.55087728, 126.8390497],
 [37.57135746, 126.8029375],
 [37.56041242, 126.8347025],
 [37.56955272, 126.808015],
 [37.56266288, 126.8235863],
 [37.52884808, 126.8419142],
 [37.55518299, 126.8573968],
 [37.55933785, 126.8208543],
 [37.56154197, 126.8543682],
 [37.54274238, 126.8364487],
 [37.53328108, 126.8465071],
 [37.55497638, 126.8611914],
 [37.55325752, 126.851179],
 [37.53891922, 126.8425844],
 [37.55850825, 126.8109074],
 [37.55518299, 126.8573968],
 [37.55454995, 126.859953],
 [37.57022098, 126.8198224],
 [37.56198289, 126.7963528],
 [37.55980495, 126.8352327],
 [37.55384873, 126.8638569],
 [37.56595623, 126.80076],
 [37.53520861, 126.8501321],
 [37.53396532, 126.8464514],
 [37.53315405, 126.8482628],
 [37.55894052, 126.8198646],
 [37.55042679, 126.8473294],
 [37.55798332, 126.8305187],
 [37.55847137, 126.834314],
 [37.53931721, 126.8445811],
 [37.54037465, 126.8513767],
 [37.53233512, 126.8576437],
 [37.55020327, 126.8670584],
 [37.57223415, 126.8328996],
 [37.57135746, 126.8029375],
 [37.52915253, 126.8389679],
 [37.54788118, 126.8194957],
 [37.55923589, 126.8544261],
 [37.56435741, 126.8191339],
 [37.55700368, 126.8658689],
 [37.5784258, 126.814972],
 [37.54052187, 126.8342201],
 [37.53724988, 126.8487882],
 [37.56692032, 126.840442],
 [37.54089599, 126.8484719],
 [37.55556128, 126.8508833],
 [37.53027443, 126.8635244],
 [37.55914479, 126.8231776],
 [37.55914479, 126.8231776],
 [37.55415316, 126.8524781],
 [37.55857186, 126.843616],
 [37.5292485, 126.8552583],
 [37.54172829, 126.8506657],
 [37.55930296, 126.8576282],
 [37.56926255, 126.8230977],
 [37.56359139, 126.8520051],
 [37.5606042, 126.8331376],
 [37.56861933, 126.8272734],
 [37.56061436, 126.8369065],
 [37.56743505, 126.8405586],
 [37.56861315, 126.8257454],
 [37.55689398, 126.8434156],
 [37.55187917, 126.8679949],
 [37.56103625, 126.8385751],
 [37.55341924, 126.8707444],
 [37.55089579, 126.8354392],
 [37.53854996, 126.8472067],
 [37.54489072, 126.8331902],
 [37.53770917, 126.8506142],
 [37.56205514, 126.8524701],
 [37.56266403, 126.8075362],
 [37.5606042, 126.8331376],
 [37.57442995, 126.8371898],
 [37.55959936, 126.8372279],
 [37.54836093, 126.8535514],
 [37.56297051, 126.8391903],
 [37.53115375, 126.8491874],
 [37.57135746, 126.8029375],
 [37.5291466, 126.842034],
 [37.58094148, 126.8133584],
 [37.55231284, 126.8494733],
 [37.57101653, 126.8465254],
 [37.55449989, 126.8519974],
 [37.54983093, 126.8752348],
 [37.53595896, 126.8466922],
 [37.57093874, 126.8413419],
 [37.56627008, 126.8430443],
 [37.55040169, 126.8623927],
 [37.57393401, 126.8100282],
 [37.55770687, 126.8612291],
 [37.52925925, 126.8452567],
 [37.53280929, 126.8388207],
 [37.55094194, 126.8576879],
 [37.56869061, 126.8199598],
 [37.55504992, 126.8688411],
 [37.57788962, 126.8190108],
 [37.57183435, 126.8225817],
 [37.560404, 126.8274815],
 [37.56348564, 126.8302176],
 [37.55203833, 126.8225424],
 [37.54293582, 126.8387089],
 [37.52907217, 126.842714],
 [37.53029522, 126.844313],
 [37.53931422, 126.838765],
 [37.53892735, 126.836078],
 [37.56367091, 126.8509172],
 [37.55186228, 126.875657],
 [37.56040454, 126.8587998],
 [37.55857745, 126.8124116],
 [37.56198289, 126.7963528],
 [37.55504992, 126.8688411],
 [37.55452846, 126.8549396],
 [37.53284947, 126.8475208],
 [37.55865733, 126.8321606],
 [37.54380508, 126.84742],
 [37.5783555, 126.8124598],
 [37.53552713, 126.858817],
 [37.54862093, 126.8195859],
 [37.55910054, 126.8609249],
 [37.56015848, 126.8372758],
 [37.57220657, 126.8183534],
 [37.53628646, 126.8600048],
 [37.54640289, 126.8588436],
 [37.53228787, 126.8407748],
 [37.56000961, 126.8331469],
 [37.55234466, 126.863925],
 [37.55929745, 126.8496375],
 [37.56468517, 126.8477436],
 [37.55653079, 126.8607377],
 [37.55068002, 126.8354878],
 [37.54597702, 126.8474658],
 [37.57652271, 126.812987],
 [37.5303556, 126.8412799],
 [37.53628388, 126.8560107],
 [37.55877421, 126.8033425],
 [37.54821989, 126.8492419],
 [37.55877421, 126.8033425],
 [37.53411311, 126.8570169],
 [37.56834872, 126.8418462],
 [37.53038697, 126.8630475],
 [37.55975486, 126.8292573],
 [37.57915581, 126.7980577],
 [37.56154197, 126.8543682],
 [37.56875291, 126.8407985],
 [37.56012645, 126.8376838],
 [37.5616849, 126.8449941],
 [37.56151218, 126.8121499],
 [37.54831629, 126.8508135],
 [37.55111088, 126.8649283],
 [37.560141, 126.8318545],
 [37.55684063, 126.847174],
 [37.55042679, 126.8473294],
 [37.55211257, 126.8632155],
 [37.5670837, 126.8187513],
 [37.55400939, 126.8178146],
 [37.54614106, 126.8458111],
 [37.54471728, 126.8615738],
 [37.56029758, 126.808751],
 [37.57223415, 126.8328996],
 [37.57699654, 126.8126172],
 [37.54247874, 126.8435478],
 [37.56518493, 126.8398916],
 [37.56113279, 126.8102658],
 [37.53785687, 126.8399192],
 [37.55191153, 126.8388525],
 [37.56579298, 126.8449306],
 [37.55884186, 126.8307769],
 [37.57900756, 126.800313],
 [37.53151495, 126.8632227],
 [37.55908441, 126.8279775],
 [37.52980184, 126.8399421],
 [37.55351422, 126.8305206],
 [37.53728052, 126.8399507],
 [37.54778874, 126.8774609],
 [37.55684063, 126.847174],
 [37.54233134, 126.8304125],
 [37.56854938, 126.8393414],
 [37.56648081, 126.8134407],
 [37.55908441, 126.8279775],
 [37.5585598, 126.8637174],
 [37.54224424, 126.8407678],
 [37.55787347, 126.8349005],
 [37.53604032, 126.8550526],
 [37.55225378, 126.8741912],
 [37.55684979, 126.8508862],
 [37.53152426, 126.8557892],
 [37.54224424, 126.8407678],
 [37.54096315, 126.8424397],
 [37.55679828, 126.8557876],
 [37.54468318, 126.835898],
 [37.55597965, 126.8615157],
 [37.56774694, 126.8256231],
 [37.55201593, 126.8366441],
 [37.55613362, 126.8184941],
 [37.56190888, 126.8023643],
 [37.55605681, 126.8536599],
 [37.54635915, 126.8349893],
 [37.55053388, 126.8490706],
 [37.56655998, 126.8468884],
 [37.54093761, 126.8398375],
 [37.57221016, 126.8061727],
 [37.55798332, 126.8305187],
 [37.55917295, 126.8415128],
 [37.55349666, 126.8134089],
 [37.55072146, 126.8665978],
 [37.53533535, 126.8373106],
 [37.56228526, 126.8191553],
 [37.55588201, 126.8551452],
 [37.54769887, 126.8624225],
 [37.58494455, 126.8208015],
 [37.55677857, 126.8677624],
 [37.57149495, 126.8383448],
 [37.56360935, 126.8473753],
 [37.53689012, 126.8369017],
 [37.53205881, 126.8486757],
 [37.52854485, 126.843152],
 [37.56435741, 126.8191339],
 [37.55992122, 126.8554116],
 [37.57152899, 126.8101004],
 [37.55202437, 126.8457656],
 [37.5404374, 126.8634494],
 [37.56460577, 126.8562568],
 [37.54847724, 126.8323195],
 [37.54615183, 126.8349812],
 [37.5586198, 126.8238423],
 [37.54143998, 126.836865],
 [37.54260152, 126.8349572],
 [37.55745597, 126.8437578],
 [37.53823155, 126.8450504],
 [37.53063112, 126.8381416],
 [37.55719604, 126.8274525],
 [37.53559082, 126.8413007],
 [37.56039191, 126.828987],
 [37.54425833, 126.8421737],
 [37.54722059, 126.859544],
 [37.57105285, 126.813821],
 [37.55649546, 126.8701887],
 [37.55850277, 126.8085759],
 [37.55211254, 126.8679009],
 [37.54802554, 126.8468684],
 [37.56774694, 126.8256231],
 [37.55212445, 126.8700849],
 [37.56198289, 126.7963528],
 [37.56388231, 126.8112973],
 [37.56120366, 126.8446167],
 [37.55674456, 126.8084568],
 [37.55854731, 126.8633554],
 [37.5756338, 126.8368314],
 [37.5608215, 126.8296028],
 [37.53441793, 126.8549982]]