# 1.패키지 불러오기

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 2. 데이터 불러오기

In [3]:
path = '/content/drive/MyDrive/데이터분석프로젝트/강서구 공모전/데이터/'

In [4]:
con_1 = pd.read_csv(path + '강서구 편의점.csv')
con_2 = pd.read_csv(path + '서울시 강서구 휴게음식점 인허가 정보.csv', encoding='cp949', error_bad_lines=False)

<ipython-input-4-d059f6411595>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  con_2 = pd.read_csv(path + '서울시 강서구 휴게음식점 인허가 정보.csv', encoding='cp949', error_bad_lines=False)

In [5]:
display(con_1.head(1))
display(con_2.head(1))

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,20698098,CU,강서태양점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150010e+24,베스트힐타운,서울특별시 강서구 강서로18길 146,157010,7745,NaN,1,NaN,126.853607,37.535125

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,...,공장판매직종업원수,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지
0,3150000,3150000-104-1966-07235,19661028,NaN,3,폐업,2,폐업,19941226,NaN,...,NaN,NaN,NaN,NaN,NaN,N,62.0,NaN,NaN,NaN

## 2-1. 필요한 컬럼만 추출

In [6]:
con_1.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [7]:
con_1.columns # 상호명, 지점명, 도로명주소, 경도, 위도
con_1 = con_1[['상호명','지점명','지번주소','도로명주소','경도','위도']]

con_1.head(1)

  상호명    지점명                 지번주소                 도로명주소          경도         위도
0  CU  강서태양점  서울특별시 강서구 화곡동 161-2  서울특별시 강서구 강서로18길 146  126.853607  37.535125

In [8]:
con_2.columns # 영업상태코드, 영업상태명, 사업장명, 도로명주소, 소재지면적, 좌표정보(X), 좌표정보(Y)
con_2 = con_2[['영업상태코드', '영업상태명', '사업장명', '도로명주소', '소재지면적', '좌표정보(X)', '좌표정보(Y)']]
con_2.head(1)

   영업상태코드 영업상태명 사업장명 도로명주소  소재지면적  좌표정보(X)  좌표정보(Y)
0       3    폐업   다린   NaN  62.00      NaN      NaN

## 2-2. 데이터 전처리

In [9]:
con_1.상호명.unique() # CU, 세븐일레븐, GS25, 미니스톱, 이마트24을 대상으로 추출

array(['CU', '세븐일레븐', '이마트', 'GS25등촌스타점', '썬플러스', 'CU방화진흥점', '예스플러스강서화곡점',
       '365플러스편의점화곡우리점', 'GS25', 'SK네트웍스해바라기', '세븐일레븐화곡곰달래지점', '미니스톱',
       '세븐일레븐강서등촌점', '세븐일레븐등촌역점', 'C,U정원점', 'GS25화곡대원점', '세븐일레븐마곡럭스점',
       '인더라인25', '위드미마곡에코점', '위드미강서화곡점', '헬로앨리스마켓24', '지에스더프레쉬', '올리브영',
       'GS25강서IT밸리점', '세븐일레븐공항시장점', 'GS25화곡풀향기', 'GS25방화대림점', 'CU화곡에스점',
       '세븐일레븐강서등촌로점', '이마트24', '세븐일레븐화곡중앙점', '24시편의점', 'CUSK가양주유소점',
       'GS25화곡행복점', '세븐일레븐가양프라자점B', 'CU방화오피스2호점', '세븐일레븐등촌현대점', 'CU발산수명점',
       '지에스25화곡달빛', '씨유화곡소비자', '위드미', '지에스25발산1단지', 'GS25마곡라마다점',
       'CU송정공항점', '위드미강서등촌점', '지에스25마곡14단지', '위드미가양역점', '365PLUS우장산현대점',
       '세븐일레븐강서화곡진주점', 'CU방화해피점', '위드미마곡미르웰점', 'CU화곡와이즈점', '비지에프휴먼넷904',
       '샐러디', '코리아세븐강서', '미니스톱강서우장산점', 'GS25곰달래로', '에스아이씨유', '미니스톱가양점',
       '위드미강서등마루점', '제이케이블라썸편의점', 'GS25화곡본', '인더라인25시편의점', 'CU방화행운점',
       '미니스톱화곡사거리점', '비지에프휴먼넷910', 'GS25화곡한빛', '지에스25방화대림', 'CU뉴화곡우리마을',
       '지에스25등촌캐빈', 'GEESSI신발편의점', '비지에프휴먼넷항공지원센터점',
       '세븐일레븐롯데스카이파크점롯데스카이파크점', 'GS25화곡비젼점', '데이앤나이트', '편의점사랑',
       '비지에프리테일화곡보리점', '서울식물원푸드이마트24편의점', '휴게음식점', 'GS25마곡8단지',
       '씨유한솔할인마트', '보광훼미리마트화곡수명', '편의점&카페24', '코리아세븐등촌샤르망', 'CU가양휴먼빌점',
       '위드미마곡일성점', 'GS25강서메르디앙점', 'GS25염창빌리지점', '내발산GS', 'CU강서다온점',
       '인더라인24시편의점가양점', 'CU방화오피스점', 'GS25마곡힐스테이트점', 'GS25강서타운점',
       '세븐일레븐가양한림점', 'GS25김포공항역점', 'GS25편의점', 'CU강서붐호텔점', '미니스톱비즈메트로점',
       '세븐일레븐마곡마커스점', '코리아세븐강서공항대로점', '지에스25방화샤르망', '훼미리마트화곡PMK',
       '코레일유통김포공항편의점', '지에스25화곡역매점', '백컵스', '비지에프휴먼넷901', '비지에프휴먼넷907',
       '비지에프휴먼넷906향천향교역점', 'CU발산열린점', '비지에프휴먼넷909', 'GS25강서센트레점',
       '세븐일레븐S방화역점', '씨제이올리브네트웍스송정', 'GS25화곡가로공원점', '우장산점', 'GS25발산1단지점',
       '티엠씨에이치', '지에스화곡들판점', '비지에프리테일화곡1동점', '미니스톱등촌청림점', 'GS25화곡대원',
       '편의점GS25', 'CU가양모터리움점', '세븐일레븐2872S개화산역점', '씨유티', '응응스크르',
       '지에스화곡나누리점', '착한가게24', '지에스', '헬시박스', '패밀리샵', '웨더', '코리아세븐마곡1',
       '코리아세븐화곡우장산숲점', '신구멍가게24', '코리아세븐방화방', '코리아세븐염창래미안점',
       '코리아세븐화곡자하클래식점', '온기', '코리아세븐항공지원센터점', '비지에프리테일공항',
       '코리아세븐김포공항버스정류장점', '코리아세븐가양9단지점', '코리아세븐마곡', '코리아세븐마곡이너매스점'],
      dtype=object)

In [10]:
#상호명에 CU,세븐일레븐,GS25,이마트24,지에스25,미니스톱 가 포함되는 데이터만 추출
gs_con = con_1[con_1.상호명.str.contains('CU|세븐일레븐|GS25|지에스25|이마트24|미니스톱')] # 총 326개
gs_con.head()

,상호명,지점명,지번주소,도로명주소,경도,위도
0,CU,강서태양점,서울특별시 강서구 화곡동 161-2,서울특별시 강서구 강서로18길 146,126.853607,37.535125
1,세븐일레븐,화곡수명점,서울특별시 강서구 화곡동 1068,서울특별시 강서구 강서로33길 103,126.834220,37.540522
2,세븐일레븐,강서내발산길점,서울특별시 강서구 내발산동 716-24,서울특별시 강서구 강서로45라길 35,126.834082,37.549387
3,CU,수명파크점,서울특별시 강서구 내발산동 751,서울특별시 강서구 수명로1길 110,126.824639,37.551852
4,CU,마곡아르디에점,서울특별시 강서구 마곡동 784-13,서울특별시 강서구 강서로 423,126.839341,37.563495

In [11]:
gs_con.상호명.unique()

array(['CU', '세븐일레븐', 'GS25등촌스타점', 'CU방화진흥점', 'GS25', '세븐일레븐화곡곰달래지점',
       '미니스톱', '세븐일레븐강서등촌점', '세븐일레븐등촌역점', 'GS25화곡대원점', '세븐일레븐마곡럭스점',
       'GS25강서IT밸리점', '세븐일레븐공항시장점', 'GS25화곡풀향기', 'GS25방화대림점', 'CU화곡에스점',
       '세븐일레븐강서등촌로점', '이마트24', '세븐일레븐화곡중앙점', 'CUSK가양주유소점', 'GS25화곡행복점',
       '세븐일레븐가양프라자점B', 'CU방화오피스2호점', '세븐일레븐등촌현대점', 'CU발산수명점', '지에스25화곡달빛',
       '지에스25발산1단지', 'GS25마곡라마다점', 'CU송정공항점', '지에스25마곡14단지',
       '세븐일레븐강서화곡진주점', 'CU방화해피점', 'CU화곡와이즈점', '미니스톱강서우장산점', 'GS25곰달래로',
       '미니스톱가양점', 'GS25화곡본', 'CU방화행운점', '미니스톱화곡사거리점', 'GS25화곡한빛',
       '지에스25방화대림', 'CU뉴화곡우리마을', '지에스25등촌캐빈', '세븐일레븐롯데스카이파크점롯데스카이파크점',
       'GS25화곡비젼점', '서울식물원푸드이마트24편의점', 'GS25마곡8단지', 'CU가양휴먼빌점',
       'GS25강서메르디앙점', 'GS25염창빌리지점', 'CU강서다온점', 'CU방화오피스점', 'GS25마곡힐스테이트점',
       'GS25강서타운점', '세븐일레븐가양한림점', 'GS25김포공항역점', 'GS25편의점', 'CU강서붐호텔점',
       '미니스톱비즈메트로점', '세븐일레븐마곡마커스점', '지에스25방화샤르망', '지에스25화곡역매점', 'CU발산열린점',
       'GS25강서센트레점', '세븐일레븐S방화역점', 'GS25화곡가로공원점', 'GS25발산1단지점',
       '미니스톱등촌청림점', 'GS25화곡대원', '편의점GS25', 'CU가양모터리움점', '세븐일레븐2872S개화산역점'],
      dtype=object)

In [12]:
# 상호명 잘못 저장된 데이터 수정
con_name = gs_con.상호명.unique().tolist()
con_name = [name for name in con_name if name not in ['GS25','CU','이마트24','세븐일레븐','미니스톱']]
con_name[:2]

['GS25등촌스타점', 'CU방화진흥점']

In [13]:
gs_con[gs_con.상호명.isin(con_name)].head(5)

,상호명,지점명,지번주소,도로명주소,경도,위도
6,GS25등촌스타점,등촌스타점,서울특별시 강서구 등촌동 512-7,서울특별시 강서구 등촌로39길 6,126.862002,37.545577
9,CU방화진흥점,방화진흥점,서울특별시 강서구 방화동 585-4,서울특별시 강서구 초원로 30,126.808431,37.567575
20,세븐일레븐화곡곰달래지점,화곡곰달래지점,서울특별시 강서구 화곡동 918-21,서울특별시 강서구 곰달래로 104,126.844313,37.530295
22,세븐일레븐강서등촌점,강서등촌점,서울특별시 강서구 등촌동 696-1,서울특별시 강서구 공항대로41길 43,126.845520,37.559897
25,세븐일레븐등촌역점,등촌역점,서울특별시 강서구 등촌동 507-1,서울특별시 강서구 등촌로 229-1,126.863458,37.550277

1. 상호명에 지점명이 포함된 경우 - 상호명만 남기기

In [14]:
replace_df = gs_con[gs_con.상호명.isin(con_name)] # 수정이 필요한 데이터
def replace_name():
  replace_name_list = []
  for i in replace_df.상호명:
    if 'CU' in i:
      replace_name_list.append('CU')
    elif 'GS25' in i:
      replace_name_list.append('GS25')
    elif '지에스25' in i:
      replace_name_list.append('GS25')
    elif '세븐일레븐' in i:
      replace_name_list.append('세븐일레븐')
    elif '이마트24' in i :
      replace_name_list.append('이마트24')
    elif '미니스톱' in i :
      replace_name_list.append('미니스톱')
    else:
      replace_name_list.append(i)
  return replace_name_list
replace_name_list=  replace_name()
replace_name_list
#np.unique(replace_name_list)
#gs_con.index

['GS25',
 'CU',
 '세븐일레븐',
 '세븐일레븐',
 '세븐일레븐',
 'GS25',
 '세븐일레븐',
 'GS25',
 '세븐일레븐',
 'GS25',
 'GS25',
 'CU',
 '세븐일레븐',
 '세븐일레븐',
 'CU',
 'GS25',
 '세븐일레븐',
 'CU',
 '세븐일레븐',
 'CU',
 'GS25',
 'GS25',
 'GS25',
 'CU',
 'GS25',
 '세븐일레븐',
 'CU',
 'CU',
 '미니스톱',
 'GS25',
 '미니스톱',
 'GS25',
 'CU',
 '미니스톱',
 'GS25',
 'GS25',
 'CU',
 'GS25',
 '세븐일레븐',
 'GS25',
 '이마트24',
 'GS25',
 'CU',
 'GS25',
 'GS25',
 'CU',
 'CU',
 'GS25',
 'GS25',
 '세븐일레븐',
 'GS25',
 'GS25',
 'CU',
 '미니스톱',
 '세븐일레븐',
 'GS25',
 'GS25',
 'CU',
 'GS25',
 '세븐일레븐',
 'GS25',
 'GS25',
 '미니스톱',
 'GS25',
 'GS25',
 'CU',
 '세븐일레븐']

In [15]:
np.unique(replace_name_list)

array(['CU', 'GS25', '미니스톱', '세븐일레븐', '이마트24'], dtype='<U5')

In [16]:
gs_con.loc[replace_df.index,'상호명'] = replace_name_list
gs_con.head(6)

,상호명,지점명,지번주소,도로명주소,경도,위도
0,CU,강서태양점,서울특별시 강서구 화곡동 161-2,서울특별시 강서구 강서로18길 146,126.853607,37.535125
1,세븐일레븐,화곡수명점,서울특별시 강서구 화곡동 1068,서울특별시 강서구 강서로33길 103,126.834220,37.540522
2,세븐일레븐,강서내발산길점,서울특별시 강서구 내발산동 716-24,서울특별시 강서구 강서로45라길 35,126.834082,37.549387
3,CU,수명파크점,서울특별시 강서구 내발산동 751,서울특별시 강서구 수명로1길 110,126.824639,37.551852
4,CU,마곡아르디에점,서울특별시 강서구 마곡동 784-13,서울특별시 강서구 강서로 423,126.839341,37.563495
6,GS25,등촌스타점,서울특별시 강서구 등촌동 512-7,서울특별시 강서구 등촌로39길 6,126.862002,37.545577

In [17]:
gs_con.상호명.unique()

array(['CU', '세븐일레븐', 'GS25', '미니스톱', '이마트24'], dtype=object)

In [18]:
gs_con.info() # 지점명 null값 존재

<class 'pandas.core.frame.DataFrame'>
Int64Index: 347 entries, 0 to 437
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   상호명     347 non-null    object
 1   지점명     329 non-null    object
 2   지번주소    347 non-null    object
 3   도로명주소   347 non-null    object
 4   경도      347 non-null    float64
 5   위도      347 non-null    float64
dtypes: float64(2), object(4)
memory usage: 27.1+ KB

In [19]:
gs_con[gs_con.지점명.isnull()] # 18개 -> 직접 채우기

,상호명,지점명,지번주소,도로명주소,경도,위도
17,CU,NaN,서울특별시 강서구 방화동 608-140,서울특별시 강서구 초원로16길 24,126.815049,37.566452
26,CU,NaN,서울특별시 강서구 등촌동 65-20,서울특별시 강서구 양천로 460,126.851681,37.562570
41,GS25,NaN,서울특별시 강서구 화곡동 1032-14,서울특별시 강서구 강서로35길 8,126.838403,37.542969
66,세븐일레븐,NaN,서울특별시 강서구 가양동 1488,서울특별시 강서구 허준로 198,126.860246,37.561302
82,GS25,NaN,서울특별시 강서구 화곡동 928-35,서울특별시 강서구 곰달래로16길 29,126.840366,37.528752
89,GS25,NaN,서울특별시 강서구 내발산동 742,서울특별시 강서구 강서로47길 108,126.830521,37.553514
100,세븐일레븐,NaN,서울특별시 강서구 화곡동 662-5,서울특별시 강서구 강서로 54,126.846596,37.531948
101,GS25,NaN,서울특별시 강서구 마곡동 750,서울특별시 강서구 마곡중앙로 33,126.824067,37.558036
146,세븐일레븐,NaN,서울특별시 강서구 화곡동 1073-10,서울특별시 강서구 화곡로 142,126.837569,37.540555
176,GS25,NaN,서울특별시 강서구 염창동 272-21,서울특별시 강서구 공항대로65길 51,126.869920,37.550312
184,GS25,NaN,서울특별시 강서구 화곡동 46-235,서울특별시 강서구 까치산로 72,126.847152,37.545019
196,GS25,NaN,서울특별시 강서구 방화동 874,서울특별시 강서구 양천로6길 57,126.808015,37.569553
199,GS25,NaN,서울특별시 강서구 등촌동 654-58,서울특별시 강서구 공항대로51길 17,126.857397,37.555183
226,이마트24,NaN,서울특별시 강서구 마곡동 812,서울특별시 강서구 마곡중앙로 136,126.832900,37.572234
231,GS25,NaN,서울특별시 강서구 마곡동 741,서울특별시 강서구 마곡서1로 81,126.819134,37.564357
312,이마트24,NaN,서울특별시 강서구 마곡동 795-6,서울특별시 강서구 마곡중앙6로 89,126.837276,37.560158
324,GS25,NaN,서울특별시 강서구 방화동 830-3,서울특별시 강서구 방화대로47가길 7,126.812987,37.576523
382,GS25,NaN,서울특별시 강서구 화곡동 1021,서울특별시 강서구 화곡로21길 87,126.835898,37.544683

In [20]:
temp_name = ['방화또오기점','화곡풀향기점','가양프라자점','화곡달빛점','발산1단지점','뉴마곡14단지점','염창세빛점',
 '등촌캐빈점','마곡골든점','방화샤르망점','화곡대원점']
# 해당 위치에 편의점 없는 경우 : 26,100,146,184,196,226,231
not_con_idx = [26,100,146,184,196,226,231]

In [21]:
temp_idx = gs_con[gs_con.지점명.isnull()].index
temp_idx= temp_idx.drop(not_con_idx)
temp_idx

Int64Index([17, 41, 66, 82, 89, 101, 176, 199, 312, 324, 382], dtype='int64')

In [22]:
gs_con = gs_con.drop(not_con_idx)
gs_con.loc[temp_idx,'지점명'] = temp_name

In [23]:
gs_con[gs_con.지점명.isnull()]
gs_con.reset_index(drop=True,inplace = True)

In [24]:
# 중복 데이터 확인
gs_con[gs_con.duplicated(['상호명','지점명'], keep = False)] # 확인
drop_idx = [50,298,169,312,232]
gs_con = gs_con.drop(drop_idx)
gs_con.reset_index(drop=True,inplace = True)

In [25]:
gs_con[gs_con.duplicated(['상호명','지점명'], keep = False)] # 확인
# 세븐일레븐 - 마곡마커스점 존재 X

,상호명,지점명,지번주소,도로명주소,경도,위도
259,세븐일레븐,마곡마커스점,서울특별시 강서구 마곡동 774-12,서울특별시 강서구 마곡동로 55,126.833147,37.560010
276,세븐일레븐,마곡마커스점,서울특별시 강서구 마곡동 774-9,서울특별시 강서구 마곡중앙6로 42,126.831855,37.560141

In [26]:
gs_con = gs_con.drop([259,276])
gs_con.reset_index(drop=True,inplace = True)

gs_con[gs_con.duplicated(['상호명','지점명'], keep = False)] # 확인

Empty DataFrame
Columns: [상호명, 지점명, 지번주소, 도로명주소, 경도, 위도]
Index: []

In [27]:
len(gs_con) # 333개

333

In [ ]:
# gs_con.to_csv(path+'./강서구편의점_전처리.csv', index=False) # 전처리한 데이터 내보내기

In [30]:
gs_con[['상호명','지점명','도로명주소']].loc[:157].to_csv(path+'/전처리_데이터/강서구편의점_목록_1.csv', index=False)
gs_con[['상호명','지점명','도로명주소']].loc[157:].to_csv(path+'/전처리_데이터/강서구편의점_목록_2.csv', index=False)

In [ ]:
con_2

,영업상태코드,영업상태명,사업장명,도로명주소,소재지면적,좌표정보(X),좌표정보(Y)
0,3,폐업,다린,NaN,62.00,NaN,NaN
1,3,폐업,코보다방,NaN,65.25,182974.746871,451121.648101
2,3,폐업,빌,NaN,16.07,185642.804833,448020.429847
3,3,폐업,샘다방,NaN,74.16,183375.296606,451710.622010
4,3,폐업,수,NaN,64.40,NaN,NaN
...,...,...,...,...,...,...,...
5258,1,영업/정상,씨유 등촌디앤써밋점,"서울특별시 강서구 공항대로 521, 1층 102호 (등촌동)",3.30,187951.778251,449928.922348
5259,1,영업/정상,크크커피(방화점),"서울특별시 강서구 초원로 18, 1층 (방화동)",81.27,182917.158635,451723.999968
5260,1,영업/정상,아프리카라운지(언라토),"서울특별시 강서구 하늘길 38, 김포공항, 롯데몰, 스카이시티 MF층 (방화동)",46.00,182524.823836,451438.250897
5261,1,영업/정상,아드망(Ademain),"서울특별시 강서구 화곡로18길 41, 1층 101호 (화곡동, 에이엔캐슬)",27.00,185468.659913,448493.329703
5262,1,영업/정상,세븐일레븐 마곡벽산점,"서울특별시 강서구 양천로47길 118, 상가동 1층 104,105호 (마곡동, 마곡...",3.30,185605.353349,452617.040420

In [ ]:
 con_2.info() # 도로명주소, 소재지면적, 좌표정보에 NULL값 존재

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5263 entries, 0 to 5262
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   영업상태코드   5263 non-null   int64
 1   영업상태명    5263 non-null   object
 2   사업장명     5263 non-null   object
 3   도로명주소    3907 non-null   object
 4   소재지면적    5149 non-null   object
 5   좌표정보(X)  4864 non-null   float64
 6   좌표정보(Y)  4864 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 287.9+ KB

In [ ]:
con_2.영업상태코드.value_counts() # 3 : 폐업 , 1: 영업/정상

3    3289
1    1974
Name: 영업상태코드, dtype: int64

In [ ]:
# 1. 영업 중인 사업장만 필터링
con_open = con_2[con_2.영업상태코드 == 1]
con_open = con_open.reset_index(drop=True)
con_open.head(3)

,영업상태코드,영업상태명,사업장명,도로명주소,소재지면적,좌표정보(X),좌표정보(Y)
0,1,영업/정상,수정다방,서울특별시 강서구 방화동로 119 (방화동),79.57,183331.992987,452094.582441
1,1,영업/정상,모란,서울특별시 강서구 양천로 606 (등촌동),52.78,188017.676607,450332.811349
2,1,영업/정상,까치다방,"서울특별시 강서구 방화동로 49, 지하1층 (방화동, 1동)",87.35,183272.778942,451439.459176

In [ ]:
# 2. 사업장명 - CU,씨유,세븐일레븐,GS25,이마트24,지에스25,미니스톱 가 포함되는 데이터만 추출 
gs_open = con_open[con_open.사업장명.str.contains('CU|세븐일레븐|GS25|지에스25|이마트24|미니스톱|씨유')] # 총 346개
gs_open = gs_open.reset_index() # 사업장명 -> 상호명/지점명으로 나누기
gs_open

,index,영업상태코드,영업상태명,사업장명,도로명주소,소재지면적,좌표정보(X),좌표정보(Y)
0,39,1,영업/정상,미니스톱가양점,서울특별시 강서구 양천로 461 (가양동),6.60,186875.994185,451205.835119
1,41,1,영업/정상,세븐일레븐(발산점),"서울특별시 강서구 강서로47길 25, 1층 (내발산동, 1동)",2.20,185332.474160,450055.415911
2,42,1,영업/정상,세븐일레븐(등촌5호점),"서울특별시 강서구 강서로68길 12, 1층 (등촌동, 3동 인방빌딩)",8.59,185932.035421,451560.536862
3,43,1,영업/정상,세븐일레븐(개화산역점),"서울특별시 강서구 양천로 34, 1층 (방화동, 2동)",3.07,182941.057623,452258.458332
4,44,1,영업/정상,세븐일레븐(방화점),"서울특별시 강서구 금낭화로 146, 1층 (방화동, 3동)",2.28,183438.673656,452893.622301
...,...,...,...,...,...,...,...,...
341,1947,1,영업/정상,씨유 강서지식산업센터점,"서울특별시 강서구 양천로 401, 강서한강자이타워 1층 B104호 (가양동)",3.30,186501.233193,451485.251876
342,1950,1,영업/정상,GS25 방화제일점,"서울특별시 강서구 방화동로12길 14, 1층 (방화동)",3.30,183448.595711,451594.304080
343,1957,1,영업/정상,씨유 화곡수정점,"서울특별시 강서구 강서로18다길 8, 수정빌딩 1층 (화곡동)",3.30,186476.764914,448046.544417
344,1969,1,영업/정상,씨유 등촌디앤써밋점,"서울특별시 강서구 공항대로 521, 1층 102호 (등촌동)",3.30,187951.778251,449928.922348
345,1973,1,영업/정상,세븐일레븐 마곡벽산점,"서울특별시 강서구 양천로47길 118, 상가동 1층 104,105호 (마곡동, 마곡...",3.30,185605.353349,452617.040420

In [ ]:
# 1. 괄호 & 공백 없애기
gs_open_name_list = gs_open['사업장명']
def remove_braket():
  remove_list = []
  for i in gs_open_name_list:
    remove_list.append(i.replace( "(" , "").replace(')', "").replace(" ",""))
  return remove_list
gs_name_list_1 = remove_braket()
gs_name_list_1[:5]
# 제거 - 레즐리컵LESELYCUP,컵CUP커피,서울식물원푸드이마트24편의점스무디킹, 카페커디CAFECUDI
# 변환 - 지에스25GS25S김포공항역점,지에스25시영일점,주이마트24강서BSD센터CFF점,주이마트24김포공항

['미니스톱가양점', '세븐일레븐발산점', '세븐일레븐등촌5호점', '세븐일레븐개화산역점', '세븐일레븐방화점']

In [ ]:
remove_shop_list = ['레즐리컵LESELYCUP','컵CUP커피','서울식물원푸드이마트24편의점스무디킹', '카페커디CAFECUDI']
remove_idx = [e for i in remove_shop_list for e,x in enumerate(gs_name_list_1) if i in x]
display(gs_open.iloc[remove_idx])
gs_open.drop(remove_idx, inplace=True) # 삭제
gs_open = gs_open.reset_index()

,index,영업상태코드,영업상태명,사업장명,도로명주소,소재지면적,좌표정보(X),좌표정보(Y)
33,258,1,영업/정상,레즐리 컵 LESELY CUP,"서울특별시 강서구 양천로73길 24, 상가동 1층 105호 (염창동, 염창힐스테이트)",34.20,188756.739409,449909.661271
211,1143,1,영업/정상,컵(CUP) 커피,"서울특별시 강서구 마곡중앙2로 5, 1층 107-1호 (마곡동)",26.55,NaN,NaN
231,1230,1,영업/정상,서울식물원푸드 이마트24 편의점(스무디킹),"서울특별시 강서구 마곡동로 161, 서울식물원 식물문화센터 4층 (마곡동)",144.78,185444.000000,451896.000000
287,1608,1,영업/정상,카페 커디(CAFE CUDI),"서울특별시 강서구 공항대로 247, 퀸즈파크나인 1층 133호 (마곡동)",41.00,185365.000000,450789.000000

In [ ]:
len(gs_open)

342

In [ ]:
# 도로명 주소 -> 위도,경도로 변환을 위해 주소 수정 
import re
def modify_address():
  pattern = r'\([^)]*\)' # 괄호 안 내용 삭제
  temp = [re.sub(pattern=pattern, repl='', string= x) for x in gs_open['도로명주소']]
  temp_split = [x.split(',')[0] for x in temp]
  temp_remove = [x.replace(')',"") for x in temp_split]# 괄호 남아있는 거 삭제
  new_address = [x.rstrip() for x in temp_remove] # 왼쪽 공백 삭제
  return new_address
gs_open['도로명주소'] = modify_address()
gs_open['도로명주소'].head()

0      서울특별시 강서구 양천로 461
1    서울특별시 강서구 강서로47길 25
2    서울특별시 강서구 강서로68길 12
3       서울특별시 강서구 양천로 34
4     서울특별시 강서구 금낭화로 146
Name: 도로명주소, dtype: object

In [ ]:
from tqdm import tqdm, tqdm_pandas

tqdm.pandas()

In [ ]:
from geopy.geocoders import Nominatim
geo_local = Nominatim(user_agent='South Korea')

#위도 반환 함수
def geocoding_lat(address):
    try:
        geo = geo_local.geocode(address)
        return geo.latitude

    except:
        return 0

#경도 반환 함수
def geocoding_lon(address):
    try:
        geo = geo_local.geocode(address)
        return geo.longitude

    except:
        return 0
        
# 변환
gs_open['위도'] = gs_open['도로명주소'].progress_apply(geocoding_lat)
gs_open['경도'] = gs_open['도로명주소'].progress_apply(geocoding_lon)

 20%|██        | 70/342 [00:34<02:20,  1.93it/s]

In [ ]:
from geopy.geocoders import Nominatim
geo_local = Nominatim(user_agent='South Korea')

#위도 반환 함수
def geocoding_lat(address):
    try:
        geo = geo_local.geocode(address)
        return geo.latitude

    except:
        return 0

#경도 반환 함수
def geocoding_lon(address):
    try:
        geo = geo_local.geocode(address)
        return geo.longitude

    except:
        return 0
        
# 변환
gs_con['위도'] = gs_con['도로명주소'].progress_apply(geocoding_lat) # 기존의 편의점 데이터의 위도 경도와 geopy를 통해 변환한 위도 경도의 오차가 있어 도로명 주소를 기준으로 동일하게 변경해줌
gs_con['경도'] = gs_con['도로명주소'].progress_apply(geocoding_lon)

In [ ]:
gs_con.to_csv(path+'./전처리_데이터/강서구편의점_위경도_수정.csv', index=False) # 전처리한 데이터 내보내기

In [ ]:
gs_open = gs_open[['사업장명','도로명주소','소재지면적','위도','경도']]
gs_open.head(1)

In [ ]:
gs_open.to_csv(path+'./전처리_데이터/강서구편의점면적_위경도_수정.csv', index=False) # 전처리한 데이터 내보내기

In [ ]:
merge_df = pd.merge(left = gs_con, right = gs_open, on=['도로명주소'], how='inner')
merge_df.drop(['경도_x','위도_x'], axis=1, inplace=True)
merge_df.rename(columns = {'위도_y':'위도','경도_y':'경도'}, inplace=True)
merge_df # 210개

In [ ]:
merge_df.to_csv(path+'./전처리_데이터/강서구편의점_통합데이터.csv', index=False) # 전처리한 데이터 내보내기

## 편의점 면적 분포 확인

In [ ]:
merge_df.info() # 소재지면적 -> float로 변경

In [ ]:
merge_df.소재지면적 = merge_df.소재지면적.astype('float')

In [ ]:
merge_df.describe()['소재지면적'] # 평균 4.4m^2 , 최대 24m^2 ?

In [ ]:
plt.hist(merge_df['소재지면적'])
plt.show()

## 가양 2동 편의점 목록 추출

In [ ]:
gs_con[gs_con.지번주소.str.contains('가양')]

,상호명,지점명,지번주소,도로명주소,경도,위도
45,CU,SK가양주유소점,서울특별시 강서구 가양동 151-1,서울특별시 강서구 강서로 498,126.841961,37.569728
50,세븐일레븐,가양프라자점,서울특별시 강서구 가양동 1488,서울특별시 강서구 허준로 198,126.860246,37.561302
69,CU,906양천향교역점,서울특별시 강서구 가양동 159-3,서울특별시 강서구 양천로 341,126.840799,37.568753
76,CU,양천향교점,서울특별시 강서구 가양동 276-2,서울특별시 강서구 양천로49길 35,126.840482,37.570182
78,CU,907가양역점,서울특별시 강서구 가양동 14-61,서울특별시 강서구 양천로 485,126.854368,37.561542
86,CU,강서산업센터점,서울특별시 강서구 가양동 1498,서울특별시 강서구 양천로 401,126.847626,37.565693
124,GS25,S9양천향교역점,서울특별시 강서구 가양동 159-3,서울특별시 강서구 양천로 341,126.840799,37.568753
129,CU,강서웨스턴점,서울특별시 강서구 가양동 1461,서울특별시 강서구 허준로 47,126.846525,37.571017
142,미니스톱,가양점,서울특별시 강서구 가양동 1480-8,서울특별시 강서구 양천로 461,126.852206,37.563035
162,GS25,S9가양역점,서울특별시 강서구 가양동 14-61,서울특별시 강서구 양천로 485,126.854368,37.561542
196,CU,가양휴먼빌점,서울특별시 강서구 가양동 1479-4,서울특별시 강서구 양천로57길 13,126.852005,37.563591
218,GS25,가양2호점,서울특별시 강서구 가양동 1461,서울특별시 강서구 허준로 47,126.846525,37.571017
222,세븐일레븐,가양한림점,서울특별시 강서구 가양동 192-9,서울특별시 강서구 강서로 511,126.841342,37.570939
223,CU,가양미르웰점,서울특별시 강서구 가양동 118-1,서울특별시 강서구 강서로68길 35,126.843044,37.566270
241,GS25,강서트레벨점,서울특별시 강서구 가양동 1479-8,서울특별시 강서구 양천로57길 9-19,126.850917,37.563671
243,GS25,가양글로벌점,서울특별시 강서구 가양동 448-11,서울특별시 강서구 화곡로72길 62,126.858800,37.560405
254,미니스톱,비즈메트로점,서울특별시 강서구 가양동 449-4,서울특별시 강서구 양천로 551-17,126.860925,37.559101
288,CU,강서오토플렉스점,서울특별시 강서구 가양동 56-2,서울특별시 강서구 양천로 390,126.844931,37.565793
299,세븐일레븐,가양9단지점,서울특별시 강서구 가양동 1490,서울특별시 강서구 허준로 234,126.863717,37.558560
313,CU,가양모터리움점,서울특별시 강서구 가양동 51-3,서울특별시 강서구 양천로53길 30,126.846888,37.566560
328,CU,가양3단지점,서울특별시 강서구 가양동 1475,서울특별시 강서구 허준로 139,126.856257,37.564606